/* Album photo du club. Pour ajouter une photo : déposez-la dans img/album/ (et une miniature dans img/album/thumbs/),
   puis ajoutez une ligne ci-dessous. cat = contest | meet | party | district | life */
window.RTC_ALBUM = [
  {"src": "p07", "cat": "contest", "fr": "Affiche du concours d'Area – 7 mars 2026", "en": "Area Contest poster – 7 March 2026", "ar": "ملصق مسابقة المنطقة – 7 مارس 2026"},
  {"src": "p20", "cat": "contest", "fr": "Concours de discours en français – 7 mars 2026", "en": "French Speech Contest – 7 March 2026", "ar": "مسابقة الخطابة بالفرنسية – 7 مارس 2026"},
  {"src": "p21", "cat": "contest", "fr": "Les lauréats du concours", "en": "Contest winners", "ar": "الفائزون في المسابقة"},
  {"src": "p22", "cat": "contest", "fr": "Remise des trophées", "en": "Trophy ceremony", "ar": "تسليم الجوائز"},
  {"src": "p00", "cat": "contest", "fr": "Remise de certificats", "en": "Certificate ceremony", "ar": "تسليم الشهادات"},
  {"src": "p19", "cat": "contest", "fr": "Félicitations à nos membres", "en": "Congratulations to our members", "ar": "تهانينا لأعضائنا"},
  {"src": "p31", "cat": "party", "fr": "Le gâteau de la 300e réunion", "en": "The 300th meeting cake", "ar": "حلوى اللقاء الثلاثمائة"},
  {"src": "p32", "cat": "party", "fr": "Célébration de la 300e réunion", "en": "Celebrating the 300th meeting", "ar": "الاحتفال باللقاء الثلاثمائة"},
  {"src": "p33", "cat": "party", "fr": "300 réunions, une grande famille", "en": "300 meetings, one big family", "ar": "300 لقاء، عائلة واحدة"},
  {"src": "p34", "cat": "party", "fr": "La 300e réunion", "en": "The 300th meeting", "ar": "اللقاء الثلاثمائة"},
  {"src": "video", "video": true, "cat": "party", "fr": "Vidéo : on souffle les bougies de la 300e réunion", "en": "Video: blowing out the 300th meeting candles", "ar": "فيديو: إطفاء شموع اللقاء الثلاثمائة"},
  {"src": "p02", "cat": "district", "fr": "Gala « Heritage in Harmony » – District 107", "en": "“Heritage in Harmony” gala – District 107", "ar": "حفل «Heritage in Harmony» – المقاطعة 107"},
  {"src": "p03", "cat": "district", "fr": "Le club au gala du District", "en": "The club at the District gala", "ar": "النادي في حفل المقاطعة"},
  {"src": "p04", "cat": "district", "fr": "Conférence du District", "en": "District conference", "ar": "مؤتمر المقاطعة"},
  {"src": "p29", "cat": "district", "fr": "Soirée de gala", "en": "Gala night", "ar": "سهرة الحفل"},
  {"src": "p01", "cat": "meet", "fr": "Le Toastmaster du jour", "en": "Toastmaster of the Day", "ar": "مُسيّر اللقاء"},
  {"src": "p05", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p06", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p10", "cat": "meet", "fr": "Une réunion au Centre Iklyl", "en": "A meeting at the Iklyl Centre", "ar": "لقاء بمركز إكليل"},
  {"src": "p11", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p12", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p13", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p14", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p16", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p17", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p18", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p26", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p27", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p28", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p36", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p39", "cat": "meet", "fr": "Prix de la réunion", "en": "Meeting awards", "ar": "جوائز اللقاء"},
  {"src": "p30", "cat": "meet", "fr": "Pourquoi j'ai renouvelé – Ali El Manja", "en": "Why I renewed – Ali El Manja", "ar": "لماذا جدّدت عضويتي – علي المنجا"},
  {"src": "p09", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p15", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p24", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p25", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p38", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p08", "cat": "life", "fr": "Sortie nature entre membres", "en": "Members' outdoor day", "ar": "خرجة في الطبيعة"},
  {"src": "p23", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p35", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"},
  {"src": "p37", "cat": "life", "fr": "La vie du club", "en": "Club life", "ar": "حياة النادي"}
];
